/**
 * Lenders, providers and professional partners.
 *
 * ## Permission is the whole point of this file
 *
 * A lender's logo is that lender's trade mark. Having the file is not the same
 * as having the right to publish it, and an intermediary relationship is not
 * automatically a brand licence. So permission is data that has to be set
 * deliberately, per mark, rather than something a developer remembers to check.
 *
 * `isLogoPermitted` is the production rule and it fails closed. Every entry
 * below is `permissionConfirmed: false`, because no permission has been
 * recorded yet — see content/pending.ts providers.list.
 *
 * ## Development preview
 *
 * The firm supplied 37 marks and asked to see the marquee with real artwork
 * during review. `devLogoPreview` allows exactly that, and ONLY that:
 *
 *   - it is false whenever VERCEL_ENV === "production", so a production
 *     deployment can never publish an unpermissioned mark;
 *   - it is false under GUIDE_STRICT_CONTENT=1, so the launch-readiness build
 *     shows the same thing production would;
 *   - it can be forced off locally with GUIDE_DEV_LOGO_PREVIEW=0.
 *
 * The production gate is untouched by it. `isLogoPermitted` still returns false
 * for all 37, the marquee still labels itself as unapproved via PendingContent,
 * and `providers.list` still blocks launch. Setting permissionConfirmed on a
 * mark is what actually publishes it.
 *
 * ## Classification
 *
 * The supplied set mixes mortgage lenders, protection providers and
 * professional/platform partners. Nothing is classified yet — that is the
 * firm's call, and a wrong grouping asserts a relationship we cannot evidence.
 * Every entry is "unclassified" and the marquee shows them together. The
 * `category` axis exists so they can be split into Lenders / Providers /
 * Professional Partners later by editing data only: give each entry its
 * category and filter the list where it is consumed. No component changes.
 */

/**
 * Trimmed derivatives, generated by scripts/prepare-logos.mjs from the files as
 * supplied in public/media/lenders/. The originals are never modified, moved or
 * renamed; see public/media/lenders/README.md.
 */
const WEB_DIR = "/media/lenders/web";

/**
 * Provisional grouping. Everything is "unclassified" until the firm confirms —
 * the other members exist so the split is a data change, not a refactor.
 */
export type ProviderCategory =
  | "lender"
  | "provider"
  | "professional-partner"
  | "unclassified";

export interface Provider {
  readonly id: string;
  /** Approved display name. Doubles as the mark's alt text. */
  readonly name: string | null;
  /** Path under /media/. Null until a file is supplied. */
  readonly logo: string | null;
  readonly category: ProviderCategory;
  /**
   * Written permission from the provider, or confirmed intermediary
   * brand-usage rights covering this site, evidenced in docs/media-licences/.
   * Never set true on the basis that a file was findable, or that the firm
   * happens to deal with that lender.
   */
  readonly permissionConfirmed: boolean;
  /** Licence record filename under docs/media-licences/. */
  readonly licenceRecord: string | null;
}

export const providers: readonly Provider[] = [
  {
    id: "aldermore",
    name: "Aldermore",
    logo: `${WEB_DIR}/Aldermore-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "aviva",
    name: "Aviva",
    logo: `${WEB_DIR}/Aviva-01.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "bm-solutions",
    name: "BM Solutions",
    logo: `${WEB_DIR}/BM-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "bank-of-ireland-uk",
    name: "Bank of Ireland UK",
    logo: `${WEB_DIR}/Bank-ireland-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "barclays",
    name: "Barclays",
    logo: `${WEB_DIR}/Barclays-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "chl-mortgages",
    name: "CHL Mortgages",
    logo: `${WEB_DIR}/Chl-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "clydesdale-bank",
    name: "Clydesdale Bank",
    logo: `${WEB_DIR}/Clydesdale-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "co-operative-bank",
    name: "The Co-operative Bank",
    logo: `${WEB_DIR}/Co-operative-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "fleet-mortgages",
    name: "Fleet Mortgages",
    logo: `${WEB_DIR}/Fleet-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "foundation-home-loans",
    name: "Foundation Home Loans",
    logo: `${WEB_DIR}/Foundation-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "godiva-mortgages",
    name: "Godiva Mortgages",
    logo: `${WEB_DIR}/Godiva-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "guardian-1821",
    name: "Guardian 1821",
    logo: `${WEB_DIR}/Guardian1821-01.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "halifax",
    name: "Halifax",
    logo: `${WEB_DIR}/Halifax-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "hsbc-life",
    name: "HSBC Life",
    logo: `${WEB_DIR}/Hsbc-life-01.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "hsbc-uk",
    name: "HSBC UK",
    logo: `${WEB_DIR}/Hsbc-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "kensington",
    name: "Kensington",
    logo: `${WEB_DIR}/Kensington-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "lv",
    name: "LV= Liverpool Victoria",
    logo: `${WEB_DIR}/LV-01.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "legal-and-general",
    name: "Legal & General",
    logo: `${WEB_DIR}/Legal-general-01.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "metlife",
    name: "MetLife",
    logo: `${WEB_DIR}/Metlife-01.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "metro-bank",
    name: "Metro Bank",
    logo: `${WEB_DIR}/Metro-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "national-friendly",
    name: "National Friendly",
    logo: `${WEB_DIR}/National-friendly-01.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "natwest",
    name: "NatWest",
    logo: `${WEB_DIR}/Natwest-logo-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "onefamily",
    name: "OneFamily",
    logo: `${WEB_DIR}/Onefamily-01.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "principality",
    name: "Principality Building Society",
    logo: `${WEB_DIR}/Principality-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "royal-london",
    name: "Royal London",
    logo: `${WEB_DIR}/Royal-london-02.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "santander",
    name: "Santander",
    logo: `${WEB_DIR}/Santander-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "scottish-widows",
    name: "Scottish Widows",
    logo: `${WEB_DIR}/Scottish-widows-01.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "skipton",
    name: "Skipton Building Society",
    logo: `${WEB_DIR}/Skipton-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "source",
    name: "Source",
    logo: `${WEB_DIR}/Source-01.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "the-exeter",
    name: "The Exeter",
    logo: `${WEB_DIR}/The-exeter-1.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "the-mortgage-works",
    name: "The Mortgage Works",
    logo: `${WEB_DIR}/The-mortgage-works-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "together",
    name: "Together",
    logo: `${WEB_DIR}/Together-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "tsb",
    name: "TSB",
    logo: `${WEB_DIR}/Tsb-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "vitality",
    name: "Vitality",
    logo: `${WEB_DIR}/Vitality-03.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "zurich",
    name: "Zurich",
    logo: `${WEB_DIR}/Zurich-03.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "accord-mortgages",
    name: "Accord Mortgages",
    logo: `${WEB_DIR}/accord-nobg.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
  {
    id: "ipipeline",
    name: "iPipeline",
    logo: `${WEB_DIR}/iPipeline-01.png`,
    category: "unclassified",
    permissionConfirmed: false,
    licenceRecord: null,
  },
];

/**
 * The production rule. A mark is publishable only with permission on record.
 * Do not loosen this — loosen the data, per mark, once the evidence exists.
 */
export const isLogoPermitted = (provider: Provider): boolean =>
  provider.logo !== null &&
  provider.name !== null &&
  provider.permissionConfirmed &&
  provider.licenceRecord !== null;

/**
 * DEVELOPMENT ONLY — render supplied marks that have no permission recorded,
 * so the marquee can be reviewed with real artwork.
 *
 * Hard off in production. See the note at the top of this file.
 */
export const devLogoPreview: boolean =
  process.env.VERCEL_ENV !== "production" &&
  process.env.GUIDE_STRICT_CONTENT !== "1" &&
  process.env.GUIDE_DEV_LOGO_PREVIEW !== "0";

/** What the marquee actually renders, permission rule plus the dev preview. */
export const canDisplayLogo = (provider: Provider): boolean =>
  isLogoPermitted(provider) ||
  (devLogoPreview && provider.logo !== null && provider.name !== null);

/** Marks that will actually render right now. Empty in production today. */
export const displayableProviders = (): readonly Provider[] =>
  providers.filter(canDisplayLogo);

/** True when the strip is showing artwork nobody has cleared for publication. */
export const showingUnpermissionedPreview = (): boolean =>
  displayableProviders().some((provider) => !isLogoPermitted(provider));

export const providersHeading = "Lenders & Providers We Work With";
