/** Generates docs/seo-route-migration.md from the route and redirect data. */
import { writeFileSync, readFileSync } from "node:fs";
import { allServicePages } from "../content/service-pages/index.ts";
import { redirects } from "../content/redirects.ts";


const liveRouteCount = allServicePages.length + 29 + 4 + 4 + 4;

const sourceUrls = readFileSync("reference/current-guide-site/source-urls.txt", "utf8")
  .split("\n")
  .map((line) => line.trim())
  .filter((line) => line.startsWith("https://guidefs.co.uk"))
  .map((line) => line.replace("https://guidefs.co.uk", "") || "/");

const byLegacy = new Map<string, string>();
for (const entry of redirects) byLegacy.set(entry.source, entry.destination);

type Row = { old: string; next: string; action: string; note: string };
const rows: Row[] = [];

for (const url of sourceUrls) {
  if (url === "/") {
    rows.push({ old: "/", next: "/", action: "KEEP", note: "Homepage." });
    continue;
  }
  if (url.endsWith(".pdf")) {
    rows.push({
      old: url,
      next: url,
      action: "KEEP",
      note: "Legal PDF. Path preserved so external and regulatory references resolve.",
    });
    continue;
  }
  if (url === "/contact") {
    rows.push({ old: url, next: "/contact", action: "KEEP", note: "Same path." });
    continue;
  }
  const destination = byLegacy.get(url);
  if (destination) {
    const owner = allServicePages.find(
      (page) => `/${page.parent}/${page.slug}` === destination,
    );
    rows.push({
      old: url,
      next: destination,
      action: "301 REDIRECT",
      note: owner
        ? `Owned by ${owner.title}.`
        : "Structural destination.",
    });
    continue;
  }
  rows.push({ old: url, next: "—", action: "REVIEW", note: "No destination assigned." });
}

const unmapped = rows.filter((row) => row.action === "REVIEW");
const covered = rows.length - unmapped.length;

const doc = `# SEO route migration

Generated by \`scripts/seo-doc.ts\` from \`content/redirects.ts\` and
\`lib/routes.ts\`. Do not edit by hand — regenerate with \`pnpm seo:doc\`.

**${rows.length}** legacy URLs from the 2026-08-29 crawl. **${covered}** have a
destination; **${unmapped.length}** need review.

New routes live: **${liveRouteCount}**.

## Principles

- No casual many-to-one consolidation. Each legacy service page keeps its own
  destination, preserving long-tail search value (docs/02-decisions.md D-002).
- Product-explainer pages moved under \`/mortgages/guides/\` rather than
  competing with circumstance-led service pages for the same intent.
- The two legal PDFs keep their exact existing paths.
- Redirects are derived from each service page's own \`legacyUrls\`, so a
  renamed slug cannot orphan an inbound link.

## Mapping

| Old URL | New URL | Action | Note |
| --- | --- | --- | --- |
${rows.map((row) => `| \`${row.old}\` | \`${row.next}\` | ${row.action} | ${row.note} |`).join("\n")}

${
  unmapped.length > 0
    ? `## Needs review\n\n${unmapped.map((row) => `- \`${row.old}\``).join("\n")}\n`
    : "All legacy URLs have a destination.\n"
}
## External dependencies, not redirected

| URL | Status |
| --- | --- |
| \`https://client.guidemortgages.co.uk\` | External client portal. Linked, not rebuilt. |
| \`https://crm.guidemortgages.co.uk\` | External adviser portal. Linked, not rebuilt. |
| \`https://calcs.webprocentral.co.uk\` | WEBPRO calculator embeds. Replaced by Guide-owned calculators; licensing must be confirmed before assuming the embeds remain available. |
| \`https://www.googletagmanager.com\` | Analytics. GTM container ID still required from the firm. |
`;

writeFileSync("docs/seo-route-migration.md", doc);
console.log(`SEO doc written: ${rows.length} legacy URLs, ${covered} mapped, ${unmapped.length} to review.`);
